package br.gov.pr.maringa.ubs.enums;

public enum TipoDeMedico {

    CARDIOLOGISTA,
    CLINICO_GERAL,
    DERMATOLOGISTA,
    ENDOCRINOLOGISTA,
    GASTROENTEROLOGISTA,
    GINECOLOGISTA,
    NEUROLOGISTA,
    OFTALMOLOGISTA,
    ORTOPEDISTA,
    OTORRINOLARINGOLOGISTA,
    PEDIATRA,
    PSIQUIATRA,
    UROLOGISTA;


}
